### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by balupton** [Nxt3/material-design-syntax#1]

**Comment by Nxt3** [comment]
I'll be honest--I can't seem to find anything that would make for an interesting screenshot. If you have some technical looking stuff, please, by all means--submit it to me. I work in Java, and for school assignments at that--it doesn't showcase the colors well enough.

Suggestions?

**Comment by Nxt3** [comment]
I've added a screenshot of a Java file I wrote. If you have something better, feel free to suggest it. Otherwise, this issue is closed for now.
