### ISSUE TITLE
Deprecated selector in `material-design-syntax/index.less`

### ISSUE THREAD

**Issue by henryraygan** [Nxt3/material-design-syntax#6]
In `material-design-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.syntax--css .syntax--punctuation.syntax--definition.keyword` => `.syntax--css .syntax--punctuation.syntax--definition.syntax--keyword`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Nxt3** [comment]
This has been fixed for a few weeks now. Are you on the latest version? It's been fixed since v2.x+

**Comment by Nxt3** [comment]
Oops. I'm not sure how I missed this. It will be fixed later today. Thank you for catching this.

**Comment by Nxt3** [comment]
This has been fixed in v2.6. Thanks!
